{
 "title": "iptnetflow",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "srcnamespace",
    "label": "Source namespace",
    "query": {
     "query": "label_values(netflow_connection_count, srcnamespace)"
    }
   },
   {
    "name": "dstnamespace",
    "label": "Destination namespace",
    "query": {
     "query": "label_values(netflow_connection_count, srcnamespace)"
    }
   },
   {
    "name": "srchost",
    "label": "Src",
    "query": {
     "query": "label_values(netflow_connection_count{srcnamespace=~\"$srcnamespace\",dstnamespace=~\"$dstnamespace\"}, srchost)"
    }
   },
   {
    "name": "dsthost",
    "label": "Dst",
    "query": {
     "query": "label_values(netflow_connection_count{srcnamespace=~\"$srcnamespace\",dstnamespace=~\"$dstnamespace\"}, dsthost)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Request/Response flow rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (srcnamespace,dstnamespace) (rate(netflow_connection_count{dstnamespace=~\"$dstnamespace\",srcnamespace=~\"$srcnamespace\",srchost=~\"$srchost\",dsthost=~\"$dsthost\"}[1m]))",
     "legendFormat": "{{srcnamespace}} -> {{dstnamespace}}"
    }
   ]
  },
  {
   "title": "Namespase Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (srcnamespace,dstnamespace) (rate(netflow_connection_bytes{dstnamespace=~\"$dstnamespace\",srcnamespace=~\"$srcnamespace\",srchost=~\"$srchost\",dsthost=~\"$dsthost\"}[5m])) * 8",
     "legendFormat": "{{srcnamespace}} -> {{dstnamespace}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request/Response rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (srchost,dsthost,srcnamespace,dstnamespace) (rate(netflow_connection_count{dstnamespace=~\"$dstnamespace\",srcnamespace=~\"$srcnamespace\",srchost=~\"$srchost\",dsthost=~\"$dsthost\"}[1m]))",
       "legendFormat": "{{srchost}}.{{srcnamespace}} -> {{dsthost}}.{{dstnamespace}}"
      }
     ]
    },
    {
     "title": "Bandwith",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (srchost,srcnamespace,dsthost,dstnamespace) (rate(netflow_connection_bytes{dstnamespace=~\"$dstnamespace\",srcnamespace=~\"$srcnamespace\",srchost=~\"$srchost\",dsthost=~\"$dsthost\"}[5m])) * 8",
       "legendFormat": "{{srchost}}.{{srcnamespace}} -> {{dsthost}}.{{dstnamespace}}"
      }
     ]
    }
   ]
  }
 ]
}